// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2_RHFrDcO9nPaMoUtGP8xnY_ZzgmhooM',
    appId: '1:789305111724:web:4599b1248dd3cb26951b09',
    messagingSenderId: '789305111724',
    projectId: 'flutter-notifications-271d8',
    authDomain: 'flutter-notifications-271d8.firebaseapp.com',
    storageBucket: 'flutter-notifications-271d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD32uL58IvZa-A3W04A27UBQrqF6KOdyfY',
    appId: '1:789305111724:android:d33bea06e604c708951b09',
    messagingSenderId: '789305111724',
    projectId: 'flutter-notifications-271d8',
    storageBucket: 'flutter-notifications-271d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE7v7nWxbVhTI5e5NT4zVS93j0GcoLKJE',
    appId: '1:789305111724:ios:7328adfab2eca711951b09',
    messagingSenderId: '789305111724',
    projectId: 'flutter-notifications-271d8',
    storageBucket: 'flutter-notifications-271d8.appspot.com',
    iosBundleId: 'com.example.adminUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE7v7nWxbVhTI5e5NT4zVS93j0GcoLKJE',
    appId: '1:789305111724:ios:5e0d9890e2a3c2dc951b09',
    messagingSenderId: '789305111724',
    projectId: 'flutter-notifications-271d8',
    storageBucket: 'flutter-notifications-271d8.appspot.com',
    iosBundleId: 'com.example.adminUi.RunnerTests',
  );
}
